/**
 * Server-side thumbnails — generated by background worker, served from cache.
 * Frontend only requests thumbnails that are confirmed ready on the server.
 * This prevents hammering the Telegram API with on-demand generation requests.
 */

function getBase() {
  return import.meta.env.VITE_API_URL || '/api';
}

function getToken() {
  return localStorage.getItem('airnotes_token') || '';
}

export function getThumbnailUrl(fileId) {
  const token = getToken();
  const base = getBase();
  return `${base}/files/${encodeURIComponent(fileId)}/thumbnail${token ? '?token=' + encodeURIComponent(token) : ''}`;
}

export function hasThumbnail(fileType) {
  return fileType === 'pdf' || fileType === 'epub' || fileType === 'video';
}

// ── Ready set — only show thumbnails that are cached on server ────────────────
let _readySet = new Set();
let _loaded = false;
let _loading = false;

export async function loadReadyThumbnails() {
  if (_loaded || _loading) return _readySet;
  _loading = true;
  try {
    const { api } = await import('./api');
    const res = await api.getReadyThumbnails();
    _readySet = new Set(res.ready || []);
    _loaded = true;
    // Refresh every 30 seconds to pick up newly generated thumbnails
    setInterval(async () => {
      try {
        const r = await api.getReadyThumbnails();
        _readySet = new Set(r.ready || []);
      } catch {}
    }, 30000);
  } catch {}
  _loading = false;
  return _readySet;
}

export function isThumbnailReady(fileId) {
  return _readySet.has(fileId);
}

// Legacy no-ops
export async function generatePdfThumbnail() { return null; }
export async function generateThumbnailsBatch() { return {}; }
